sonar.projectKey=Lupet007_ecoflow
sonar.organization=lupet007

sonar.projectName=EcoFlow
sonar.projectVersion=1.0

sonar.sources=backend/src/main/java,frontend/src,pipeline
sonar.tests=backend/src/test/java
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.java.binaries=backend/target/classes

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.mvn/**,**/mvnw,**/mvnw.cmd,**/*.drawio,**/coverage/**,**/cypress/videos/**,**/cypress/screenshots/**,**/package-lock.json,**/target/**