spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/ecoflow
spring.datasource.username=ecoflow
spring.datasource.password=ecoflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=8fK2mL9xQpR7vT4yN6zA1cD5eF8gH3jK9mP2sW4xY7bN5vC1