spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:ecoflow}
spring.datasource.username=${DB_USER:ecoflow}
spring.datasource.password=${DB_PASSWORD:ecoflow}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=8fK2mL9xQpR7vT4yN6zA1cD5eF8gH3jK9mP2sW4xY7bN5vC1